### PR TITLE
Updated how 'Show advanced settings' works

### PR DESCRIPTION
**Pull request by waydabber**
This PR has the following changes:

- Moved `Show advanced settings` to the Displays tab with a local scope only.
- Now all other panes will show all settings by default.
- Reorganized the General to be more logical.
- Removed unnecessary 'Disable software fallback' option.

This is how the Displays tab now looks like with advanced settings enabled (see the setting in the bottom right corner) and using light theme:

Screen Shot 2021-10-14 at 21 01 45

This is how the tab looks like with advanced disabled with dark theme:

Screen Shot 2021-10-14 at 21 08 39

Note: I was extra careful not to introduce any changes that mess up localizatons as we would not want an other round of translations before the full release.

Let me know if you don't like it, I am open to suggestions.

### CODE REVIEW

**Comment by the0neyouseek** [comment]
You can leave it there in General I think

**Comment by waydabber** [comment]
All right. I just don't know how the two buttons (Check for update, Reset Preferences) will look so close to each other.

**Comment by the0neyouseek** [comment]
@waydabber Indeed, I hadn't thought about it… Maybe moving it in the About tab would make more sense then. Feel free to try and see how it feels and choose the one you like best

**Comment by waydabber** [comment]
I cannot seem to find a suitable place for the button, it look silly everywhere. :] The best option might be to move the Reset Preferences button to the About tab next to the Website button as a third one but that is not entirely logical.

**Pull request merged**
