### PR TITLE
Various Enhancements

### PR DESCRIPTION
**Pull request by reitermarkus**
- Update to Swift 5
- Switch to Carthage
- German Translation
- Switch to DDC.swift
- Refactoring

### CODE REVIEW

**Comment by reitermarkus** [comment]
@the0neyouseek, I changed the `hideDisplayOsd` function to check for the vendor and model number instead of the display name.

**Comment by reitermarkus** [comment]
@the0neyouseek, ok, I added a whitelist now.

**Comment by the0neyouseek** [comment]
I'll build and publish an updated version tonight

**Comment by reitermarkus** [comment]
@the0neyouseek, I made a release draft so you only have to build it. 😉

**Comment by the0neyouseek** [comment]
@reitermarkus Thanks for all your work ! If you have time, could you take a look through the open issues and close the ones that should now be fixed by this PR (or even #59). Have a nice day !

**Pull request merged**
