### PR TITLE
Fixed contrast slider not being set with brightness (#132)

### LINKED ISSUE #132: Contrast slider is not set to its previous value when increasing brightness if "Lower contrast after brightness" is enabled
**Repro Steps:**
1. Make sure "Lower contrast after brightness" is turned on, brightness is currently >0 and contrast is currently >0
2. Lower the brightness to 0
3. Check the brightness and contrast sliders - they should both be 0
4. Raise the brightness by one level
5. Check the brightness and contrast sliders

**Expected Results:**
- The brightness slider should be set to level one
- The contrast slider should be set back to its former value before being set to 0 by the brightness pref

**Actual Results:**
- The brightness slider is set to level one
- The contrast slider is still set to 0

ezgif-3-8c46ac37e4df

### PR DESCRIPTION
**Pull request by scorpiondev**
ezgif-3-9fae8444d6b9

Fixes #132

### CODE REVIEW

**Comment by JoniVR** [comment]
Great fix, only thing I've found about this is that the contrast doesn't go back up if you restart the app after lowering it all the way. 

Reproduce:
1. Turn down brightness all the way until contrast is 0
2. Restart MonitorControl
3. Turn up the brightness (either before or after polling is finished)
The contrast will remain 0.

This is not really a problem with your PR as it fixes most of the issue, but we might want to fix that too in the future. 

Either we can do this in a separate PR/commit or we do it in this one. I could perhaps look into fixing this in this PR but I'm pretty busy currently so it might take a while before I can get to it. I'm also not sure if that would cause conflicts with your other PR or not though.. 

So your call @scorpiondev, do you want to merge this first and we can fix that issue later or do it in this one?

**Comment by scorpiondev** [comment]
@JoniVR: Thanks for the review, and yeah, nice pickup on that issue.

What's happening here is as follows (assuming contrast is already set to >0 and preference to lower contrast after brightness is enabled):
1. Set brightness to 0 - contrast DDC value is set to 0 but NOT persisted to user defaults (Display.swift, line 165)
3. Restart the app - slider items are regenerated, and contrast DDC value is currently 0, so when the app reads it, it persists that value to user defaults (Utils.swift, line 49)
4. Set brightness to >0 - app reads the preference for contrast in order to restore the previous value, but it's already been set and persisted to 0, so it never gets increased back to its previous value

There are a couple of ways we could tackle this:
- _(naïve but simple way)_ When setting brightness to >0, if "lower contrast after brightness" is enabled, simply set the contrast to 100 if the persisted value for contrast is 0
- _(proper but more complex way)_ When setting brightness to 0, save a separate "restore" preference item (e.g.: 18-restore-<identifier>) for the contrast's previous value. When subsequently setting brightness to >0 - including if this happens after an app restart - restore contrast to the value of the restore preference item.  If contrast is manually set from the menu slider, delete the restore preference item.

Happy to go down either path - the former is quick to implement but might annoy users who fiddle with exact contrast values, the latter handles the issue more comprehensively but introduces further risk because it's more complex. Let me know what you think :)

**Comment by JoniVR** [comment]
I like the second option better to be honest. Also because my default contrast value is 70, but for some people it might be a different value. We could always solve this by simply allowing the user to set a default contrast value but I think the second option is simply the better approach.

**Comment by scorpiondev** [comment]
Done - I've implemented the restore value in such a way that we can do the same thing with other DDC commands in the future, if you so wish.

**Comment by JoniVR** [comment]
I don't know if it may have something to do with my specific config but your fix doesn't work reliable anymore for me now. Especially restoring contrast back to previous value. Sometimes it works the first time but that's it.

ezgif com-video-to-gif

**Comment by scorpiondev** [comment]
Ah, there's an exception condition - if you reduce your brightness to 0 (which reduces contrast to 0), then press brightness down again, the restore value will be overwritten with the current DDC value for contrast (which is 0).

The condition which causes this issue (that is, being able to set brightness to 0 when it's already at 0) will be fixed by my performance enhancements, but in the meantime, I can put a fix into this branch to prevent the condition from occurring.

Also noticed a couple of other exception scenarios which I'm not sure whether to also fix with this PR:
- setting brightness to 0/>0 from the slider doesn't adjust contrast when the lower contrast after brightness preference is enabled
- disabling the lower contrast after brightness preference means that the restore value for contrast will no longer get updated, so if the preference is enabled again, the contrast would potentially be restored to an incorrect value
- if the contrast slider preference is disabled, but the lower contrast after brightness preference is enabled, the contrast DDC value never gets read, and hence will be stuck at 0 once brightness is set to 0

**Comment by scorpiondev** [comment]
I've fixed these scenarios for now:
- setting brightness to 0/>0 from the slider doesn't adjust contrast when the lower contrast after brightness preference is enabled; and
- if you reduce your brightness to 0 (which reduces contrast to 0), then press brightness down again, the restore value will be overwritten with the current DDC value for contrast (which is 0)

**Comment by scorpiondev** [comment]
Squashed and ready to merge 👍

**Pull request merged**
