### PR TITLE
🇺🇦 Ukrainian localisation update for the new version of app #137

### LINKED ISSUE #137: Ukrainian localisation has to be updated for the new version of app
I will do it.
Pull request will be pushed soon

### PR DESCRIPTION
**Pull request by kikiwora**
Just an update for new app version, including SF Symbols for more clear actions

Closes #137

### CODE REVIEW

**Comment by JoniVR** [comment]
Could you also add the Ukrainian flag to the readme? I'll try to look into this PR after the other bug fixes but it may take some time for me to get to it. Thanks for the PR though! :)

**Comment by kikiwora** [comment]
Yeah, I will :) Thx!

6 жовт. 2019 р. о 20:48 Joni Van Roost <notifications@github.com> пише:

﻿

Could you also add the Ukrainian flag to the readme? I'll try to look into this PR after the other bug fixes but it may take some time for me to get to it. Thanks for the PR though! :)

**Comment by kikiwora** [comment]
OK, I will remove them. Didn’t actually check backward-compatibility with previous systems, my fault.
That was indeed a bad idea to put those in localization :)

8 жовт. 2019 р. о 00:21 Joni Van Roost <notifications@github.com<mailto:notifications@github.com>> написав(ла):


@JoniVR requested changes on this pull request.

While I like the idea of using the SF symbols, they look broken in earlier versions of macOS (like Mojave). We also don't use them in other languages and so I think it's better to remove them for now. Might be something we can consider in the future though.

[image]<https://user-images.githubusercontent.com/7591717/66349099-63aa2680-e958-11e9-9822-5a1a7e48272a.png>

**Comment by JoniVR** [comment]
Looks good! Thanks for the PR!

**Pull request merged**
